version: '3.8'
name: finance-tracker

services:
  postgres:
    image: tbished/finance-postgres:latest
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: finance-user
      POSTGRES_PASSWORD: change_me
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance-user -d finance"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - finance_network

  finance-tracker-be:
    image: tbished/finance-server:v12-postgres
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/finance
      spring.datasource.username: finance-user
      spring.datasource.password: change_me
      spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
      spring.datasource.driverClassName: org.postgresql.Driver
      ml.service.url: http://ml-service:8000/api/v1/predict/batch
    ports:
      - "8800:40010"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - finance_network

  finance-ui:
    image: tbished/finance-ui:latest
    ports:
      - "3050:80"
    environment:
      - REACT_APP_BACKEND_URL=http://finance-tracker-be:40010/api
    depends_on:
      finance-tracker-be:
        condition: service_started
    networks:
      - finance_network

  finance-tracker-ml:
    image: tbished/finance-tracker-ml:latest
    ports:
      - "8000:8000"
    volumes:
      - ml_models:/app/models
    environment:
      - MODEL_DIR=/app/models
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8080"]
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=finance
      - DB_USER=finance-user
      - DB_PASSWORD=change_me
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - finance_network

volumes:
  postgres_data:
  ml_models:

networks:
  finance_network:
    driver: bridge