server.port: 40010
spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    driverClassName: org.postgresql.Driver
    username: finance-user
    password: change_me
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect