server.port: 40010
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/finance
    driverClassName: org.postgresql.Driver
    username: OverideMe
    password: OverideMe
  jpa:
    database-platform: com.bishop.FinanceTracker.config.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: finance
