create table transaction (
  TRANSACTION_ID BIGINT UNSIGNED not null,
  CATEGORY varchar(100) not null,
  AMOUNT float(4) not null,
  TRANSACTION_DATE BIGINT UNSIGNED not null,
  COMMENT varchar(100),
  ESSENTIAL bool not null,
  CREATE_DATE BIGINT UNSIGNED not null,
  PRIMARY KEY(TRANSACTION_ID)
  );

 CREATE TABLE category (
  CATEGORY_NAME VARCHAR(100) NOT NULL,
  CREATE_DATE BIGINT UNSIGNED not null,
  PRIMARY KEY (CATEGORY_NAME)
  );